/**
 * Regenerates supabase/seed.sql from the placeholder data in src/data.
 * Usage: npm run db:seed-sql
 */
import { writeFileSync } from "node:fs";
import { restaurants } from "../src/data/restaurants";

const rows = restaurants.map((r) => ({
  slug: r.slug,
  name: r.name,
  name_ar: r.nameAr ?? null,
  tagline: r.tagline,
  tagline_ar: r.taglineAr ?? null,
  cuisine: r.cuisine,
  price_level: r.priceLevel,
  neighborhood: r.neighborhood,
  neighborhood_ar: r.neighborhoodAr ?? null,
  address: r.address,
  address_ar: r.addressAr ?? null,
  phone: r.phone,
  timezone: r.timezone,
  currency: r.currency,
  accent: r.accent,
  cover: r.cover ?? null,
  hours: r.hours,
  links: r.links,
  source: r.source,
  verified_at: r.verifiedAt,
  google_menu_link: r.googleMenuLink,
  menus: r.menus,
  stats: r.stats,
  // Seeded as already claimed to demo the verified state (no owner row, so nobody can edit it).
  claimed_at: r.claimed ? `${r.verifiedAt}T12:00:00Z` : null,
}));

const json = JSON.stringify(rows);
if (json.includes("$seed$")) throw new Error("Seed data contains the $seed$ quote delimiter");

const columns =
  "slug, name, name_ar, tagline, tagline_ar, cuisine, price_level, neighborhood, neighborhood_ar, address, address_ar,\n  phone, timezone, currency, accent, cover, hours, links, source, verified_at, google_menu_link, menus, stats, claimed_at";

const sql = `-- Placeholder restaurants (generated by scripts/export-seed.ts). Re-runnable.
insert into mealtree.restaurants (
  ${columns}
)
select ${columns}
from jsonb_to_recordset($seed$${json}$seed$::jsonb) as x(
  slug text, name text, name_ar text, tagline text, tagline_ar text, cuisine text[], price_level smallint,
  neighborhood text, neighborhood_ar text, address text, address_ar text, phone text, timezone text, currency text,
  accent text, cover text, hours jsonb, links jsonb, source text, verified_at date, google_menu_link boolean,
  menus jsonb, stats jsonb, claimed_at timestamptz
)
on conflict (slug) do update set
  name = excluded.name, name_ar = excluded.name_ar, tagline = excluded.tagline, tagline_ar = excluded.tagline_ar,
  cuisine = excluded.cuisine, price_level = excluded.price_level, neighborhood = excluded.neighborhood,
  neighborhood_ar = excluded.neighborhood_ar, address = excluded.address, address_ar = excluded.address_ar,
  phone = excluded.phone, timezone = excluded.timezone, currency = excluded.currency, accent = excluded.accent, cover = excluded.cover, hours = excluded.hours,
  links = excluded.links, source = excluded.source, verified_at = excluded.verified_at,
  google_menu_link = excluded.google_menu_link, menus = excluded.menus, stats = excluded.stats;
`;

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), sql);
console.log(`Wrote supabase/seed.sql (${rows.length} restaurants)`);
