/**
 * Regenerates supabase/seed.sql from the placeholder data in src/data.
 * Usage: npm run db:seed-sql
 */
import { writeFileSync } from "node:fs";
import { restaurants } from "../src/data/restaurants";

const rows = restaurants.map((r) => ({
  slug: r.slug,
  name: r.name,
  tagline: r.tagline,
  cuisine: r.cuisine,
  price_level: r.priceLevel,
  neighborhood: r.neighborhood,
  address: r.address,
  phone: r.phone,
  timezone: r.timezone,
  accent: r.accent,
  cover: r.cover ?? null,
  hours: r.hours,
  links: r.links,
  source: r.source,
  verified_at: r.verifiedAt,
  google_menu_link: r.googleMenuLink,
  menus: r.menus,
  stats: r.stats,
  // Seeded as already claimed to demo the verified state (no owner row, so nobody can edit it).
  claimed_at: r.claimed ? `${r.verifiedAt}T12:00:00Z` : null,
}));

const json = JSON.stringify(rows);
if (json.includes("$seed$")) throw new Error("Seed data contains the $seed$ quote delimiter");

const columns =
  "slug, name, tagline, cuisine, price_level, neighborhood, address, phone, timezone, accent, cover,\n  hours, links, source, verified_at, google_menu_link, menus, stats, claimed_at";

const sql = `-- Placeholder restaurants (generated by scripts/export-seed.ts). Re-runnable.
insert into mealtree.restaurants (
  ${columns}
)
select ${columns}
from jsonb_to_recordset($seed$${json}$seed$::jsonb) as x(
  slug text, name text, tagline text, cuisine text[], price_level smallint, neighborhood text, address text,
  phone text, timezone text, accent text, cover text, hours jsonb, links jsonb, source text, verified_at date,
  google_menu_link boolean, menus jsonb, stats jsonb, claimed_at timestamptz
)
on conflict (slug) do update set
  name = excluded.name, tagline = excluded.tagline, cuisine = excluded.cuisine, price_level = excluded.price_level,
  neighborhood = excluded.neighborhood, address = excluded.address, phone = excluded.phone,
  timezone = excluded.timezone, accent = excluded.accent, cover = excluded.cover, hours = excluded.hours,
  links = excluded.links, source = excluded.source, verified_at = excluded.verified_at,
  google_menu_link = excluded.google_menu_link, menus = excluded.menus, stats = excluded.stats;
`;

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), sql);
console.log(`Wrote supabase/seed.sql (${rows.length} restaurants)`);
